[project]
name = "metta-spider"
version = "0.1.0"
dependencies = ["cogames"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/metta_spider"]
